name: Intro CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pipenv"

      - name: Install Pipenv
        run: pip install pipenv

      - name: Initialize Python
        run: pipenv --python 3.11

      - name: Install dependencies
        run: pipenv install --deploy --dev

      - name: Run tests
        run: pipenv run pytest
